#version 430 core

layout(local_size_x = 128) in;

layout(std430, binding = 0) buffer InputBuffer {
    float inputs[];
};
layout(std430, binding = 1) buffer OutputBuffer {
    float outputs[];
};
layout(std430, binding = 2) buffer WeightsBuffer {
    float weights[];
};
layout(std430, binding = 3) buffer BiasesBuffer {
    float biases[];
};


float activation(float x)
{
    return 1.0 / (1.0 + exp(-x));
}

void main()
{
    uint neuron_num = gl_globalinvocationid.x;
    if(neuron_num >= outputs.length) return;
    
    uint current_sample = invocation/outputs.length;
    uint output_neuron_num = invocation%outputs.length;
    int input_sample_start = current_sample*inputs.length;

    float sum = 0.f;
    for(int i = input_sample_start; i < inputs.length+input_sample_start; i++) {
       sum += inputs[i] * weights[outputs.length* i + output_neuron_num]; 
    }
    sum += biases[output_neuron_num]; 

    outputs[neuron_num] = activation(sum);
}
